// supabase/functions/agents-orchestrator/agents/ag008/catalog/pattern-codes.catalog.ts
// Closed Pattern Code Catalog for AG-008 (v1.0)
// Frozen under Token: AG008-PATTERN-CATALOG-001

export const APPROVED_FAILURE_PATTERN_CODES = [
  'NO_SIGNIFICANT_FAILURE_PATTERN',
  'FAILURE_RECURRENCE',
  'FAILURE_REINCIDENCE',
  'FAILURE_FREQUENCY_INCREASE',
  'FAILURE_TREND_UP',
  'FAILURE_TREND_DOWN',
  'FAILURE_TREND_STABLE',
  'FAILURE_CONCENTRATION',
  'MACHINE_FAILURE_CONCENTRATION',
  'DEPARTMENT_FAILURE_CONCENTRATION',
  'FAILURE_TYPE_CONCENTRATION',
  'CROSS_MACHINE_PATTERN',
  'SEASONAL_PATTERN',
  'INSUFFICIENT_HISTORY_FOR_SEASONALITY',
  'PARTIAL_FAILURE_DATA',
  'INSUFFICIENT_TREND_DATA',
  'UNATTRIBUTED_FAILURES_PRESENT',
  'DATA_QUALITY_LIMITATION',
  'RECURRENCE_WITHOUT_REINCIDENCE_PROOF',
  'ALERT_CONDITION_PRESENT'
] as const;

export type FailurePatternCode = typeof APPROVED_FAILURE_PATTERN_CODES[number];

export function isValidFailurePatternCode(code: string): boolean {
  return APPROVED_FAILURE_PATTERN_CODES.includes(code as FailurePatternCode);
}
