// supabase/functions/agents-orchestrator/agents/ag009/ag009_1/errors/preventive-error-catalog.ts
// Standard Error Catalog for AG-009.1 Preventive Connector (§56 PRD-AG-009.1)

export const PREVENTIVE_ERROR_CODES = {
  INVALID_EVENT: 'INVALID_EVENT',
  INVALID_CONTRACT: 'INVALID_CONTRACT',
  INVALID_SOURCE: 'INVALID_SOURCE',
  INVALID_DATE: 'INVALID_DATE',

  MACHINE_NOT_FOUND: 'MACHINE_NOT_FOUND',
  MACHINE_INACTIVE: 'MACHINE_INACTIVE',
  INVALID_DEPARTMENT: 'INVALID_DEPARTMENT',

  PREVENTIVE_YEAR_MISMATCH: 'PREVENTIVE_YEAR_MISMATCH',
  PREVENTIVE_YEARLY_DUPLICATE: 'PREVENTIVE_YEARLY_DUPLICATE',

  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_INACTIVE: 'SERVICE_INACTIVE',

  CHECKLIST_NOT_FOUND: 'CHECKLIST_NOT_FOUND',
  CHECKLIST_INACTIVE: 'CHECKLIST_INACTIVE',

  MISSING_REQUIRED_DATA: 'MISSING_REQUIRED_DATA',
  PARTS_INFORMATION_MISSING: 'PARTS_INFORMATION_MISSING',

  DUPLICATE_EVENT: 'DUPLICATE_EVENT',
  POSSIBLE_DUPLICATE: 'POSSIBLE_DUPLICATE',

  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVAL_INVALID: 'APPROVAL_INVALID',
  APPROVAL_ALREADY_USED: 'APPROVAL_ALREADY_USED',
  APPROVAL_PAYLOAD_MISMATCH: 'APPROVAL_PAYLOAD_MISMATCH',

  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  AGENT_CONNECTOR_DISABLED: 'AGENT_CONNECTOR_DISABLED',
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR'
} as const;

export type PreventiveErrorCode = typeof PREVENTIVE_ERROR_CODES[keyof typeof PREVENTIVE_ERROR_CODES];

export class PreventiveConnectorError extends Error {
  public readonly code: PreventiveErrorCode;
  public readonly details?: Record<string, any>;

  constructor(code: PreventiveErrorCode, message: string, details?: Record<string, any>) {
    super(`[AG-009.1] ${code}: ${message}`);
    this.name = 'PreventiveConnectorError';
    this.code = code;
    this.details = details;
  }
}
