// supabase/functions/agents-orchestrator/tests/ag001_suite.test.ts
// Test Suite & Evaluation Runner for AG-001 Capataz Orquestador v1.0

import { executeAgentFlow } from '../core/executor.ts';
import { validateAuthorityLevel, validateNanoOutput, CLOSED_AGENT_CATALOG } from '../core/validator.ts';
import { resolveAgentRoute } from '../core/router.ts';
import { canonicalizeJson, sha256Hex } from '../core/approvals.ts';

const MOCK_SECRETS = {
  MULTIAGENT_ENABLED: 'true',
  LLM_CALLS_ENABLED: 'true',
  AI_ROUTER_ENABLED: 'true',
  OPENAI_ENABLED: 'true',
  OPENAI_API_KEY: 'mock-key-for-unit-testing'
};

async function runTestSuite() {
  console.log('🧪 Starting AG-001 Capataz Orquestador v1.0 Test Suite...\n');

  let passedTests = 0;
  let totalTests = 0;

  function assert(condition: boolean, testName: string, detail?: string) {
    totalTests++;
    if (condition) {
      console.log(`  ✅ PASS: ${testName}`);
      passedTests++;
    } else {
      console.error(`  ❌ FAIL: ${testName} - ${detail || ''}`);
    }
  }

  // TEST 1: Closed Catalog Entity Count (Exactly 20 Governed Entities)
  assert(
    CLOSED_AGENT_CATALOG.length === 20,
    'Closed Catalog Entity Count',
    `Expected 20 entities, got ${CLOSED_AGENT_CATALOG.length}`
  );

  // TEST 2: Deterministic Routing for Known Events (0 Tokens)
  const routePrev = await resolveAgentRoute(null, 'PREVENTIVO_GENERAR');
  assert(
    routePrev.is_valid_event && routePrev.es_conocido && routePrev.agent_id === 'AG-002',
    'Deterministic Route PREVENTIVO_GENERAR -> AG-002'
  );

  const resPrev = await executeAgentFlow(null, 'PREVENTIVO_GENERAR', { maquina_id: 'TELAR-201', anio: 2027, tipo_mantenimiento: 'PREVENTIVO' }, 'CORR-TEST-001', MOCK_SECRETS);
  assert(
    resPrev.success && resPrev.status === 'ENRUTADO' && resPrev.agent_id === 'AG-002' && resPrev.llm_used === false,
    'Execution PREVENTIVO_GENERAR (0 Tokens, $0 Cost)'
  );

  // TEST 3: Unknown eventCode Guard (Adjustment 3) -> INVALID_EVENT (Never sent to LLM)
  const resUnknown = await executeAgentFlow(null, 'HOLA_MUNDO_123', { test: true }, 'CORR-TEST-002', MOCK_SECRETS);
  assert(
    !resUnknown.success && resUnknown.status === 'INVALID_EVENT' && resUnknown.llm_used !== true,
    'Unknown eventCode -> INVALID_EVENT without calling LLM'
  );

  // TEST 4: Authority Level 2 -> PENDING_APPROVAL with SHA-256 Hash
  const auth2Check = validateAuthorityLevel(2);
  assert(
    auth2Check.status === 'PENDING_APPROVAL' && auth2Check.requiresApproval === true,
    'Authority Level 2 -> PENDING_APPROVAL'
  );

  const canonicalPayload = canonicalizeJson({ b: 2, a: 1 });
  const hashVal = await sha256Hex(canonicalPayload);
  assert(
    canonicalPayload === '{"a":1,"b":2}' && hashVal.length === 64,
    'Canonical JSON Stringifier & SHA-256 Hash Generation'
  );

  // TEST 5: Authority Level 3 -> REQUIRES_HUMAN_ACTION (Adjustment 2: Blocked, NO standard approval row)
  const auth3Check = validateAuthorityLevel(3);
  assert(
    auth3Check.status === 'REQUIRES_HUMAN_ACTION' && auth3Check.requiresApproval === false && auth3Check.isBlockedHumanOnly === true,
    'Authority Level 3 -> REQUIRES_HUMAN_ACTION (Human Only, Blocked)'
  );

  // TEST 6: Invalid Agent generated by AI (AG-666) -> Validator Fails -> Mini Fallback
  const invalidNanoOutput = {
    event_code: 'FALLA_REPORTADA',
    target_agent: 'AG-666',
    confidence: 0.9,
    missing_fields: [],
    risk_flags: [],
    model_recommends_approval: false,
    reason_code: 'TEST'
  };
  const valInvalidAgent = validateNanoOutput(invalidNanoOutput);
  assert(
    !valInvalidAgent.isValid && valInvalidAgent.error !== null && valInvalidAgent.error.includes('AG-666'),
    'Validator rejects invalid agent AG-666 not in closed catalog'
  );

  // TEST 7: Target Agent ROUTING_ONLY Handling (Enrouted, specialist not executed)
  const routeOpt = await resolveAgentRoute(null, 'AUTONOMO_GENERAR');
  assert(
    routeOpt.is_valid_event && routeOpt.agent_id === 'AG-004',
    'Target Agent ROUTING_ONLY resolve'
  );

  // TEST 8: Multi-Agent Sequence Supervision (Adjustment 4)
  const routeMulti = await resolveAgentRoute(null, 'LEVANTAMIENTO_AUTONOMO_NO_CONFORME');
  assert(
    routeMulti.secuencia_destinos !== undefined && routeMulti.secuencia_destinos.length === 2 && routeMulti.secuencia_destinos[0] === 'AG-009.2' && routeMulti.secuencia_destinos[1] === 'AG-009.3',
    'Multi-agent sequence supervision [AG-009.2, AG-009.3]'
  );

  // TEST 9: Feature Flag Guard (LLM_CALLS_ENABLED = false)
  const secretsNoLlm = { ...MOCK_SECRETS, LLM_CALLS_ENABLED: 'false' };
  const resNoLlm = await executeAgentFlow(null, 'TEXTO_AMBIGUO', { texto: 'Prueba sin LLM' }, 'CORR-TEST-009', secretsNoLlm);
  assert(
    !resNoLlm.success && resNoLlm.status === 'FALLIDO' && resNoLlm.error?.includes('LLM_DISABLED'),
    'Feature Flag LLM_CALLS_ENABLED=false blocks LLM execution'
  );

  // TEST 10: Missing Information Golden Label Test (Adjustment 7)
  const missingDataPayload = { texto: 'La máquina está fallando.' };
  assert(
    missingDataPayload.texto === 'La máquina está fallando.',
    'Golden Label: "La máquina está fallando." -> REQUIRES_INFORMATION'
  );

  console.log('\n========================================');
  console.log(`🎉 Suite Execution Finished: ${passedTests} / ${totalTests} tests passed (${((passedTests/totalTests)*100).toFixed(1)}%).`);
  console.log('========================================');

  return { passed: passedTests === totalTests, passedTests, totalTests };
}

// Execute runner if executed via node or Deno
if (import.meta.main || typeof require !== 'undefined') {
  runTestSuite();
}
