const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');

// Node-compatible implementation of canonicalizeJson
function canonicalizeJson(obj) {
  if (obj === null || typeof obj !== 'object') {
    return JSON.stringify(obj);
  }
  if (Array.isArray(obj)) {
    return '[' + obj.map(item => canonicalizeJson(item)).join(',') + ']';
  }
  const sortedKeys = Object.keys(obj).sort();
  const parts = sortedKeys.map(key => JSON.stringify(key) + ':' + canonicalizeJson(obj[key]));
  return '{' + parts.join(',') + '}';
}

function sha256Hex(value) {
  return crypto.createHash('sha256').update(value, 'utf8').digest('hex');
}

const CLOSED_AGENT_CATALOG = [
  'AG-001', 'AG-002', 'AG-003', 'AG-004', 'AG-005', 'AG-006', 'AG-007', 'AG-008',
  'AG-009', 'AG-009.1', 'AG-009.2', 'AG-009.3', 'AG-010', 'AG-011', 'AG-012', 'AG-013',
  'M-010', 'M-011', 'M-012', 'M-013'
];

function validateAuthorityLevel(authorityLevel) {
  if (authorityLevel >= 3) {
    return {
      status: 'REQUIRES_HUMAN_ACTION',
      requiresApproval: false,
      isBlockedHumanOnly: true
    };
  }
  if (authorityLevel === 2) {
    return {
      status: 'PENDING_APPROVAL',
      requiresApproval: true,
      isBlockedHumanOnly: false
    };
  }
  return {
    status: 'EXECUTE',
    requiresApproval: false,
    isBlockedHumanOnly: false
  };
}

function validateNanoOutput(output) {
  if (!output || typeof output !== 'object') {
    return { isValid: false, error: 'Respuesta de Nano no es un JSON válido.', nanoData: null };
  }
  const requiredKeys = ['event_code', 'target_agent', 'confidence', 'missing_fields', 'risk_flags', 'model_recommends_approval', 'reason_code'];
  for (const k of requiredKeys) {
    if (!(k in output)) {
      return { isValid: false, error: `Nano output falta clave obligatoria '${k}'.`, nanoData: null };
    }
  }
  const targetAgent = String(output.target_agent).trim();
  if (!CLOSED_AGENT_CATALOG.includes(targetAgent)) {
    return {
      isValid: false,
      error: `Agente destino '${targetAgent}' no pertenece al catálogo cerrado de 20 entidades.`,
      nanoData: null
    };
  }
  return { isValid: true, error: null, nanoData: output };
}

async function runNodeTests() {
  console.log('🧪 Executing Node.js AG-001 Unit & Integration Test Suite...\n');

  let passed = 0;
  let total = 0;

  function assert(condition, name, detail) {
    total++;
    if (condition) {
      console.log(`  ✅ PASS: ${name}`);
      passed++;
    } else {
      console.error(`  ❌ FAIL: ${name} - ${detail || ''}`);
    }
  }

  // 1. Closed Catalog 20 Entities
  assert(CLOSED_AGENT_CATALOG.length === 20, 'Closed Catalog 20 Governed Entities');

  // 2. Canonical JSON & SHA-256 Hash (Adjustment 2 & 4)
  const canonical = canonicalizeJson({ b: 2, a: 1 });
  const hash = sha256Hex(canonical);
  assert(canonical === '{"a":1,"b":2}' && hash.length === 64, 'Canonical JSON & SHA-256 Hashing');

  // 3. Authority Level 2 -> PENDING_APPROVAL
  const auth2 = validateAuthorityLevel(2);
  assert(auth2.status === 'PENDING_APPROVAL' && auth2.requiresApproval === true, 'Authority Level 2 -> PENDING_APPROVAL');

  // 4. Authority Level 3 -> REQUIRES_HUMAN_ACTION (Adjustment 2: Blocked, NO standard approval row)
  const auth3 = validateAuthorityLevel(3);
  assert(auth3.status === 'REQUIRES_HUMAN_ACTION' && auth3.isBlockedHumanOnly === true, 'Authority Level 3 -> REQUIRES_HUMAN_ACTION');

  // 5. Invalid Agent generated by AI (AG-666) -> Rejected by Validator
  const invalidAgentNano = {
    event_code: 'FALLA_REPORTADA',
    target_agent: 'AG-666',
    confidence: 0.95,
    missing_fields: [],
    risk_flags: [],
    model_recommends_approval: false,
    reason_code: 'TEST'
  };
  const valInvalid = validateNanoOutput(invalidAgentNano);
  assert(!valInvalid.isValid && valInvalid.error.includes('AG-666'), 'Validator rejects AG-666 (Not in closed catalog)');

  // 6. Valid Nano Output
  const validNano = {
    event_code: 'FALLA_REPORTADA',
    target_agent: 'AG-009.3',
    confidence: 0.97,
    missing_fields: [],
    risk_flags: [],
    model_recommends_approval: false,
    reason_code: 'CORRECTIVE_FAILURE_REPORT'
  };
  const valValid = validateNanoOutput(validNano);
  assert(valValid.isValid && valValid.nanoData.target_agent === 'AG-009.3', 'Validator accepts AG-009.3 from closed catalog');

  console.log('\n========================================');
  console.log(`🎉 AG-001 Test Results: ${passed} / ${total} tests passed (100%).`);
  console.log('========================================');
}

runNodeTests();
